### ISSUE TITLE
New logo proposal for FreeAmp app

### ISSUE THREAD

**Issue by ammarraisafti** [recoilme/freemp#18]
Hello admin, I want to offer a new and free logo minimalist design for FreeAmp app. This logo is very pretty, Namely combined Letter M and P, so it will give a better impression on FreeAmp app. This logo is my special design for you.If you willing to accept it, you simply reply to this proposal, I will send you a new logo of this file. And if you want other color variations or want to request a little modification. Please tell me. I will do it soon. Thanks

![new logo app freemp](https://user-images.githubusercontent.com/37721970/42129204-062f4a86-7ce8-11e8-8b39-c5603ae75521.png)

Greetings

**Comment by recoilme** [comment]
Sorry, I'm sick and missed the notification.
First of all, many thanks for your work!
Everything is done very professionally, but I'm afraid that the logo may merge against the dark background of the application. But I would love to try and attach a screenshot with the application. It is a pity that there is no reference to winamp, I was inspired by it

**Comment by recoilme** [comment]
@ammarraisafti oh. not so cute as you expected i think

![photo_2018-07-09_14-30-07](https://user-images.githubusercontent.com/417177/42448092-b74ea800-8384-11e8-8ba0-1e0070292e65.jpg)

**Comment by recoilme** [comment]
![photo_2018-07-09_14-32-26](https://user-images.githubusercontent.com/417177/42448158-f893f720-8384-11e8-988e-6b83bbff8707.jpg)
old icon looks more buaty i think(

**Comment by recoilme** [comment]
![empty_artwork1](https://user-images.githubusercontent.com/417177/42448227-2b40f2f4-8385-11e8-9ff5-68c3a013e2fc.png)
i attach old icon developed by Ponomarenko Ilya source

**Comment by recoilme** [comment]
colors, padding, transparency - all matters in icon
